### ISSUE TITLE
Illegal character Curator/Executor

### ISSUE THREAD

**Issue by sinaure** [sonata-nfv/tng-vnv-curator#39]
Executing test: 
https://pre-int-vnv-bcn.5gtango.eu/validation-and-verification/tests/958d71e7-9713-4581-b4e6-2b9e3f533640

on ENV: pre-int-vnv-bcn

curator/executor error:

java.net.URISyntaxException: Illegal character in path at index 96: http://tng-vnv-curator:6200/api/v1/test-preparations/4dbc5db7-334a-435c-84d4-9a0756e813bb/tests/<test_uuid>/cancel
 

Full error stack trace

http://logs.sonata-nfv.eu/search?rangetype=absolute&fields=source%2Ccontainer_name%2Cmessage&width=2048&highlightMessage=&from=2019-12-09T11%3A33%3A13.893Z&to=2019-12-09T11%3A35%3A27.713Z&q=source%3Apre-int-vnv-bcn+AND+(container_name%3A*curator*+OR+container_name%3A*executor*+OR+container_name%3A*mqttprobe*)+

**Comment by juanlucruz** [comment]
This is not a curator issue, but executor. Probably it is a new bug there, <test_uuid> should be reemplaced by an uuid in executor.
