### ISSUE TITLE
SP unable to perform placement

### ISSUE THREAD

**Issue by sinaure** [sonata-nfv/tng-vnv-curator#42]
This is not an issue for curator....
Any idea about the causes?

2019-12-11 10:49:24.232 | pre-int-vnv-bcn | tng-vnv-curator
-- | -- | --
Received parameters from SP: [{'nsi_uuid': None, 'platform': {'platform_type': 'unknown'}, 'functions': None, 'nsi_name': 'test-industrial-pilot-ns1-tng-smpilot-ns1-k8s-qual-sp-bcn', 'error': 'Unable to perform placement.'}]

**Comment by juanlucruz** [comment]
@sinaure If this is not an issue for curator I am closing this issue and please reopen it where it should be.

I suggest you to check platform adapter log, and qual-sp-bcn log.
