### ISSUE TITLE
[Pre int vnv bcn ] 500 error test-preparations

### ISSUE THREAD

**Issue by sinaure** [sonata-nfv/tng-vnv-curator#46]
Error in curator/pl-adapter (sorry if I'm wrong the interactions of pl-adapter with the rest of components are not super clear to me: is curator that periodically send request to adapter not the opposite)

2019-12-11 16:23:19.887 | pre-int-vnv-bcn | tng-vnv-curator
-- | -- | --
172.18.0.19 - - [11/Dec/2019 16:23:19] "POST /api/v1/test-preparations/6495bd89-9beb-4a77-ac8f-a95703b68f50/service-instances/test-industrial-pilot-ns1-tng-smpilot-ns1-k8s-qual-sp-bcn/sp-ready HTTP/1.1" 500 -

**Comment by sinaure** [comment]
http://logs.sonata-nfv.eu/search?rangetype=absolute&fields=source%2Ccontainer_name%2Cmessage&width=1366&highlightMessage=&from=2019-12-11T16%3A23%3A04.890Z&to=2019-12-11T16%3A23%3A26.232Z&q=source%3Apre-int-vnv-bcn+++AND+(container_name%3A*curator*+OR+container_name%3A*executor*%2C+OR+container_name%3A*adapter*)+

**Comment by juanlucruz** [comment]
Its a platform adapter error @sinaure. Error in the request. Code is 500, to make the upper API user that is something related with the SP...

```
2019-12-11 16:23:20.232 2019-12-11 16:23:19.883373 UTC  tango.curator:core      510     after_request   I
172.18.0.19 http POST /api/v1/test-preparations/6495bd89-9beb-4a77-ac8f-a95703b68f50/service-instances/test-industrial-pilot-ns1-tng-smpilot-ns1-k8s-qual-sp-bcn/sp-ready? 500 INTERNAL SERVER ERROR 76
2019-12-11 16:23:20.232 2019-12-11 16:23:19.882892 UTC  tango.curator:core      312     prepare_environment_callback    E
Got an Exception: 'test-industrial-pilot-ns1-tng-smpilot-ns1-k8s-qual-sp-bcn'
2019-12-11 16:23:20.232 2019-12-11 16:23:19.882708 UTC  tango.curator:core      265     prepare_environment_callback    D
Callback received, contains {'error': 'error getting request status'}
2019-12-11 16:23:20.232 2019-12-11 16:23:19.882334 UTC  tango.curator:core      252     prepare_environment_callback    D
Callback received /api/v1/test-preparations/6495bd89-9beb-4a77-ac8f-a95703b68f50/service-instances/test-industrial-pilot-ns1-tng-smpilot-ns1-k8s-qual-sp-bcn/sp-ready, contains b'{"error": "error getting request status"}',Content-type: application/json
```

**Comment by sinaure** [comment]
ok related to missing K8s VIM in bcn qual SP
